"""Remove cached columns from YearData

Revision ID: a6378e08b7e5
Revises: 
Create Date: 2025-05-26 00:55:37.906661

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a6378e08b7e5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("year_data", schema=None) as batch_op:
        batch_op.alter_column(
            "sync_status",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=20),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "sync_progress",
            existing_type=sa.FLOAT(),
            type_=sa.Integer(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("year_data", schema=None) as batch_op:
        batch_op.alter_column(
            "sync_progress",
            existing_type=sa.Integer(),
            type_=sa.FLOAT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "sync_status",
            existing_type=sa.String(length=20),
            type_=sa.VARCHAR(length=50),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
